services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    
  ingest:
    build: .
    command:
      - --pg-host
      - pgdatabase
      - --pg-user
      - root
      - --pg-pass
      - root
      - --pg-db
      - ny_taxi
      - --target-table
      - yellow_taxi_trips
      - --target-table
      - zones
    depends_on:
      - pgdatabase

networks:
  default:
    name: docker-workshop-network

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: